#' @title Campaign Transaction Report
#' 
#' @description This function generates the campaign Transaction report statement and schedules the report. The API returns a job ID, which later will be used to receive the data from the API.
#' 
#' @param authToken Authentication token generated by \code{\link{doCriteoAuth}}
#' @param appToken Application Token
#' @param catalog ISSSS CATALOG modify this Vector of campaign IDs. Example: campaigns = c('12345', '01235', '98765')
#' @param metrics Vector of metrics. Example: metrics = c('clickDateTime','displayDateTime','duplicateStatus','orderValue')
#'                available metrics. clickDateTime or clickDateTimePosix or displayDateTime or displayDateTimePosix or duplicateStatus or orderValue
#' @param start Start Date, format: "YYYY-mm-dd"
#' @param end End Date, format: "YYYY-mm-dd"
#' 
#' @export
#' @return Transaction Report job ID
scedCriteoTrReport <- function(authToken, appToken, catalog, metrics, start, end){
  duration <- as.numeric(difftime(as.Date(end),as.Date(start),units=c("days")))
  if(duration>30){
    print("Time window is limited to 30 days for daily Transaction aggregation. Please reduce the time window end run scedCriteoTrReport again!")
  } else {
  
  cat = paste('<string>',catalog,'</string>\n',collapse="",sep="")
  metr = paste('<TransactionReportColumn>',metrics,'</TransactionReportColumn>\n',collapse = "",sep="")
  body = paste('<?xml version="1.0" encoding="utf-8"?>
               <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
               <soap:Header>
               <apiHeader xmlns="https://advertising.criteo.com/API/v201305">
               <authToken>', authToken ,'</authToken>
               <appToken>', appToken ,'</appToken>
               <clientVersion>3.6</clientVersion>
               </apiHeader>
               </soap:Header>
               <soap:Body>
               <scheduleTransactionReportJob xmlns="https://advertising.criteo.com/API/v201305">
               <reportJob>
			   <catalogSelector>
                 <CatalogNames>',
				 cat,                   
                 '</CatalogNames>
               </catalogSelector>
               <selectedColumns>',
               metr,
               '</selectedColumns>
               <startDate>',start,'</startDate>
               <endDate>',end,'</endDate>
               <isResultGzipped>false</isResultGzipped>
               </reportJob>
               </scheduleTransactionReportJob>
               </soap:Body>
               </soap:Envelope>', sep='')
        
          headerFields = c(Accept = "text/xml",
                           Accept = "multipart/*",
                           'Content-Type' = "text/xml; charset=utf-8",
                           SOAPAction = "https://advertising.criteo.com/API/v201305/scheduleTransactionReportJob")
        
          h = RCurl::basicTextGatherer()
          
          RCurl::curlPerform(url = "https://advertising.criteo.com/API/v201305/AdvertiserService.asmx",
                      httpheader = headerFields,
                      postfields = body,
                      writefunction = h$update
          )
          
          data <- XML::xmlParse(h$value())
          data <- XML::xmlToList(data)
          data <- data$Body$scheduleTransactionReportJobResponse$jobResponse$jobID
          attr(data, "metrics") <- metrics
          data
      }
}
